### ISSUE TITLE
New Version Overrides Meditation and other Mechanics

### ISSUE THREAD

**Issue by 0jit0** [apokryphus/eternal-hunt#5]
Can't be changed by menu or keybinds, not even by priority on MM. Manually won't work and MM either. 

Mods is amazing don't get me wrong but is starting to be too invasive. Even default keybindings for the special attacks is very obscure and the attacks are too circumstantial, some of those attacks i haven't been able to replicate after doing them by mistake spamming keys on the keyboard while in combat (Ex: Double Parry combined with Witcher Sense or something like that, What?). 

Please revamp the keybinding and menu system before adding more functions is a shame that such great work gets downgraded by ui or input method.  

Sincerely thanks a lot for the mod, is a very ambitious project and all the work and constant updates are proof of how much effort you're putting into it.

Edit: By new i meant V1.37, V1.36 Does not have the meditation issue

**Comment by apokryphus** [comment]
Yes, I override the meditation key starting in 1.38 to use my version of quick real-time meditation since there is no point in using the default vanilla one anymore. If you want to use the old one you'd have to go directly into the menus for it. I'm unlikely to change it back since I don't see much of a point in doing so.

If you're having trouble with the keybindings I would suggest rebinding keys to better utilize them, or take it slow and try to perform them with precision. They were meant to be hard to perform and have tight restrictions due to how strong they are for regular combat.

**Comment by 0jit0** [comment]
I understand, thanks a lot for your response. Will for sure follow your advice abt trying to learn how to use the mechanics better, they are too good to not use them. As for the meditation issue is not vanilla what worries me, would be amazing to have the chance to at least to give both Friendly Meditation and Preparations  priority over a timelapse. Again don't take me wrong, the mod is amazing but could it be possible to add some kind of toggle for these kinds of mechanics replacements? Thanks again for the mod itself and your response.

**Comment by apokryphus** [comment]
Hmmm sure I'll add a toggle for it actually. Or just straight up add to it everything fmed and preparations does

**Comment by 0jit0** [comment]
Oh that would be awesome. Thanks a lot for considering it thats a win win 

Wanted to update you on the mechanics issue would love to hear what you think about what i could find, the problem is in my peripherals input i guess, i can willingly replicate the special moves with only one of my three keyboards (all Logitech, similar price range/quality) but honestly no idea on what could be the issue. is there some kind of limitations for some keyboards regarding input frequency or how any keys you can press at the same time that i should have into consideration? Coincidentally my working keyboard is the one that works, nor the backup one or the gaming one would work. could it be some latency issue?

**Comment by apokryphus** [comment]
> is there some kind of limitations for some keyboards regarding input frequency or how any keys you can press at the same time that i should have into consideration?
There's a 0.4 second window for inputs that require double-tapping , but other than that not much. I will need to know which exact inputs you're having trouble with in order to help.

The falling shockwave causing guards to become aggressive is intended. Requires the player to think carefully where they land.

**Comment by 0jit0** [comment]
Understood, thanks a lot for the help!!i'm enjoying the mod a lot man. had some trouble with monsters taking too little damage and health bar not moving but i'm seeing it fixed in latest version, will download now. Again thanks a lot. The movements i have trouble with are those that need more than two keys at the same time.
